engines:
  rubocop:
    enabled: false
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
ratings:
  paths:
  - lib/**
exclude_paths:
- spec/**/*
- lib/br_invoices_pdf/nfce/parser/emission_details.rb
